---
#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  es2021: true
  node: true
  jest: true

###############
# Global Vars #
###############
# globals:

###############
# Parser vars #
###############
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  project: true
  sourceType: module

###########
# Plugins #
###########
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/recommended-type-checked'
  - 'plugin:@typescript-eslint/stylistic-type-checked'
plugins:
  - '@typescript-eslint'
#########
# Rules #
#########
# rules:
#   no-useless-escape: warn
#   semi: error
